#!/bin/sh
dehumanise() {
  for v in "${@:-$(</dev/stdin)}"
  do
    echo $v | awk \
      'BEGIN{IGNORECASE = 1}
       function printpower(n,b,p) {printf "%u\n", n*b^p; next}
       /[0-9]$/{print $1;next};
       /K(iB)?$/{printpower($1,  2, 10)};
       /M(iB)?$/{printpower($1,  2, 20)};
       /G(iB)?$/{printpower($1,  2, 30)};
       /T(iB)?$/{printpower($1,  2, 40)};
       /KB$/{    printpower($1, 10,  3)};
       /MB$/{    printpower($1, 10,  6)};
       /GB$/{    printpower($1, 10,  9)};
       /TB$/{    printpower($1, 10, 12)}'
  done
}
MAX_SIZE=`dehumanise $WATCH_DIRECTORY_MAX_SIZE`
SIZE=`du -h $WATCH_DIRECTORY |tail -n 1| cut -f1`
echo "$SIZE $WATCH_DIRECTORY_MAX_SIZE"

SIZE=`dehumanise $SIZE`
SIZE=`echo $SIZE | tr -d '\n'`
while [ "$SIZE" -gt "$MAX_SIZE" ] ; do
  printf "size: $SIZE\t>  max_size: $MAX_SIZE\n"
  

  fn=`find $WATCH_DIRECTORY -type f -printf "%T+ \t%p\n" | sort -r | tail -n 1|cut -f2`
  echo "deleting $fn"
  rm $fn
  
  # delete files within oldest directory
  # fn=`ls -1t $WATCH_DIRECTORY | tail -n 1`
  # find "$WATCH_DIRECTORY/$fn" -type f -delete

  find "$WATCH_DIRECTORY" -type d -empty -delete
  SIZE=`du -h $WATCH_DIRECTORY | tail -n 1| cut -f1`
  SIZE=`dehumanise $SIZE`
  SIZE=`echo $SIZE | tr -d '\n'`
  echo "$SIZE"
done


